-- PROJETO SMARTCOFFE_FELIPE

-- CRIAR BANCO D DADOS
-- ATIVAR BANDO DE DADOS
-- CRIAR TABELAS   

-- --------------------------------------------------- --

-- OPCIONAIS NO DIA 21/08/26
-- INSERIR DADOS 
-- CONSULTAR 

-- --------------------------------------------------- --

CREATE DATABASE IF NOT EXISTS PROJETO_SMART_COFFE;
USE PROJETO_SMART_COFFE;

CREATE TABLE IF NOT EXISTS GERENTE (
ID_GERENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF INT,
NOME VARCHAR(60),
NASCIMENTO DATE,
EMAIL VARCHAR(60),
TELEFONE VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS SMARTCOFFE (
ID_ESTABELECIMENTO INT AUTO_INCREMENT PRIMARY KEY,
FUNCIONARIOS VARCHAR(60),
HORARIOS_DE_FUNCIONAMENTO TIME,
ESTOQUE_QUANTIDADES INT
);

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIOS INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PRODUTOS (
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PROGRAMA_FIDELIDADE (
CADASTRO INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PAGAMENTO (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS REEMBOLSO (
ID_REEMBOLSO INT AUTO_INCREMENT PRIMARY KEY);

CREATE TABLE IF NOT EXISTS DELIVERY (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY);













